name: EMR Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      INSTANCE_IP: ${{ vars.INSTANCE_IP }}
      USERNAME: ${{ vars.USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GITHUB_USERNAME: ${{ secrets.GHUB_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: deploy webapp
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.INSTANCE_IP }}
        username: ${{ env.USERNAME }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu 
          sudo rm -rf openmrs-distro-referenceapplication
          git clone -b dev https://github.com/Demo-Practices/openmrs-distro-referenceapplication.git
          cd openmrs-distro-referenceapplication
          
          # Build and deploy the Docker containers
          bash <(curl -Ls https://gist.githubusercontent.com/pasinduljay/02cf2effb83c771c6f302b2ba59faf74/raw/8f1a8903b11da98510bb53f452fd8a0b35f04c53/Verification%2520for%2520Docker%2520and%2520Docker-compose)
          sudo docker compose down
          sudo docker compose build
          sudo docker compose up -d